// Package logger ...
package logger

// DLTag ...
type DLTag string

const (
	// DLTagUndefined ..
	DLTagUndefined DLTag = " _undef"
	// DLTagModuleStart ...
	DLTagModuleStart = " _com_module_start"
	// DLTagModuleStop ...
	DLTagModuleStop = " _com_module_stop"
	// DLTagConfLoad ...
	DLTagConfLoad = " _com_conf_load"
	// DLTagConfReload ...
	DLTagConfReload = " _com_conf_reload"
	// DLTagDataLoad ...
	DLTagDataLoad = " _com_data_load"
	// DLTagDataReload ...
	DLTagDataReload = " _com_data_reload"
	// DLTagMysqlFailed ...
	DLTagMysqlFailed = " _com_mysql_failed"
	// DLTagRedisFailed ...
	DLTagRedisFailed = " _com_redis_failure"
	// DLTagThriftFailed ...
	DLTagThriftFailed = " _com_thrift_failure"
	// DLTagThriftSuccess ...
	DLTagThriftSuccess = " _com_thrift_success"
	// DLTagHTTPSuccess ...
	DLTagHTTPSuccess = " _com_http_success"
	// DLTagHTTPFailed ...
	DLTagHTTPFailed = " _com_http_failure"
	// DLTagBackendRPCFailed ...
	DLTagBackendRPCFailed = " _com_interactive_failure"
	// DLTagRequestIn ...
	DLTagRequestIn = " _com_request_in"
	// DLTagRequestOut ...
	DLTagRequestOut = " _com_request_out"
	// DLTagTegPushSend ...
	DLTagTegPushSend = " _com_teg_push_send"
	// DLTagTegPushRecv ...
	DLTagTegPushRecv = " _com_teg_push_recv"
)
